// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

#ifndef PROTOBUF_api_2eproto__INCLUDED
#define PROTOBUF_api_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "options.pb.h"  // IWYU pragma: export
#include "trip.pb.h"  // IWYU pragma: export
#include "directions.pb.h"  // IWYU pragma: export
#include "info.pb.h"  // IWYU pragma: export
#include "status.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace valhalla {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_api_2eproto();
void protobuf_AssignDesc_api_2eproto();
void protobuf_ShutdownFile_api_2eproto();

class Api;

// ===================================================================

class Api : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:valhalla.Api) */ {
 public:
  Api();
  virtual ~Api();

  Api(const Api& from);

  inline Api& operator=(const Api& from) {
    CopyFrom(from);
    return *this;
  }

  static const Api& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const Api* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(Api* other);

  // implements Message ----------------------------------------------

  inline Api* New() const { return New(NULL); }

  Api* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Api& from);
  void MergeFrom(const Api& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Api* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .valhalla.Options options = 1;
  bool has_options() const;
  void clear_options();
  static const int kOptionsFieldNumber = 1;
  const ::valhalla::Options& options() const;
  ::valhalla::Options* mutable_options();
  ::valhalla::Options* release_options();
  void set_allocated_options(::valhalla::Options* options);

  // optional .valhalla.Trip trip = 2;
  bool has_trip() const;
  void clear_trip();
  static const int kTripFieldNumber = 2;
  const ::valhalla::Trip& trip() const;
  ::valhalla::Trip* mutable_trip();
  ::valhalla::Trip* release_trip();
  void set_allocated_trip(::valhalla::Trip* trip);

  // optional .valhalla.Directions directions = 3;
  bool has_directions() const;
  void clear_directions();
  static const int kDirectionsFieldNumber = 3;
  const ::valhalla::Directions& directions() const;
  ::valhalla::Directions* mutable_directions();
  ::valhalla::Directions* release_directions();
  void set_allocated_directions(::valhalla::Directions* directions);

  // optional .valhalla.Status status = 4;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 4;
  const ::valhalla::Status& status() const;
  ::valhalla::Status* mutable_status();
  ::valhalla::Status* release_status();
  void set_allocated_status(::valhalla::Status* status);

  // optional .valhalla.Info info = 20;
  bool has_info() const;
  void clear_info();
  static const int kInfoFieldNumber = 20;
  const ::valhalla::Info& info() const;
  ::valhalla::Info* mutable_info();
  ::valhalla::Info* release_info();
  void set_allocated_info(::valhalla::Info* info);

  // @@protoc_insertion_point(class_scope:valhalla.Api)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::valhalla::Options* options_;
  ::valhalla::Trip* trip_;
  ::valhalla::Directions* directions_;
  ::valhalla::Status* status_;
  ::valhalla::Info* info_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_api_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_api_2eproto();
  #endif
  friend void protobuf_AssignDesc_api_2eproto();
  friend void protobuf_ShutdownFile_api_2eproto();

  void InitAsDefaultInstance();
  static Api* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Api

// optional .valhalla.Options options = 1;
inline bool Api::has_options() const {
  return !_is_default_instance_ && options_ != NULL;
}
inline void Api::clear_options() {
  if (GetArenaNoVirtual() == NULL && options_ != NULL) delete options_;
  options_ = NULL;
}
inline const ::valhalla::Options& Api::options() const {
  // @@protoc_insertion_point(field_get:valhalla.Api.options)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return options_ != NULL ? *options_ : *default_instance().options_;
#else
  return options_ != NULL ? *options_ : *default_instance_->options_;
#endif
}
inline ::valhalla::Options* Api::mutable_options() {
  
  if (options_ == NULL) {
    options_ = new ::valhalla::Options;
  }
  // @@protoc_insertion_point(field_mutable:valhalla.Api.options)
  return options_;
}
inline ::valhalla::Options* Api::release_options() {
  // @@protoc_insertion_point(field_release:valhalla.Api.options)
  
  ::valhalla::Options* temp = options_;
  options_ = NULL;
  return temp;
}
inline void Api::set_allocated_options(::valhalla::Options* options) {
  delete options_;
  options_ = options;
  if (options) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:valhalla.Api.options)
}

// optional .valhalla.Trip trip = 2;
inline bool Api::has_trip() const {
  return !_is_default_instance_ && trip_ != NULL;
}
inline void Api::clear_trip() {
  if (GetArenaNoVirtual() == NULL && trip_ != NULL) delete trip_;
  trip_ = NULL;
}
inline const ::valhalla::Trip& Api::trip() const {
  // @@protoc_insertion_point(field_get:valhalla.Api.trip)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return trip_ != NULL ? *trip_ : *default_instance().trip_;
#else
  return trip_ != NULL ? *trip_ : *default_instance_->trip_;
#endif
}
inline ::valhalla::Trip* Api::mutable_trip() {
  
  if (trip_ == NULL) {
    trip_ = new ::valhalla::Trip;
  }
  // @@protoc_insertion_point(field_mutable:valhalla.Api.trip)
  return trip_;
}
inline ::valhalla::Trip* Api::release_trip() {
  // @@protoc_insertion_point(field_release:valhalla.Api.trip)
  
  ::valhalla::Trip* temp = trip_;
  trip_ = NULL;
  return temp;
}
inline void Api::set_allocated_trip(::valhalla::Trip* trip) {
  delete trip_;
  trip_ = trip;
  if (trip) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:valhalla.Api.trip)
}

// optional .valhalla.Directions directions = 3;
inline bool Api::has_directions() const {
  return !_is_default_instance_ && directions_ != NULL;
}
inline void Api::clear_directions() {
  if (GetArenaNoVirtual() == NULL && directions_ != NULL) delete directions_;
  directions_ = NULL;
}
inline const ::valhalla::Directions& Api::directions() const {
  // @@protoc_insertion_point(field_get:valhalla.Api.directions)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return directions_ != NULL ? *directions_ : *default_instance().directions_;
#else
  return directions_ != NULL ? *directions_ : *default_instance_->directions_;
#endif
}
inline ::valhalla::Directions* Api::mutable_directions() {
  
  if (directions_ == NULL) {
    directions_ = new ::valhalla::Directions;
  }
  // @@protoc_insertion_point(field_mutable:valhalla.Api.directions)
  return directions_;
}
inline ::valhalla::Directions* Api::release_directions() {
  // @@protoc_insertion_point(field_release:valhalla.Api.directions)
  
  ::valhalla::Directions* temp = directions_;
  directions_ = NULL;
  return temp;
}
inline void Api::set_allocated_directions(::valhalla::Directions* directions) {
  delete directions_;
  directions_ = directions;
  if (directions) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:valhalla.Api.directions)
}

// optional .valhalla.Status status = 4;
inline bool Api::has_status() const {
  return !_is_default_instance_ && status_ != NULL;
}
inline void Api::clear_status() {
  if (GetArenaNoVirtual() == NULL && status_ != NULL) delete status_;
  status_ = NULL;
}
inline const ::valhalla::Status& Api::status() const {
  // @@protoc_insertion_point(field_get:valhalla.Api.status)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return status_ != NULL ? *status_ : *default_instance().status_;
#else
  return status_ != NULL ? *status_ : *default_instance_->status_;
#endif
}
inline ::valhalla::Status* Api::mutable_status() {
  
  if (status_ == NULL) {
    status_ = new ::valhalla::Status;
  }
  // @@protoc_insertion_point(field_mutable:valhalla.Api.status)
  return status_;
}
inline ::valhalla::Status* Api::release_status() {
  // @@protoc_insertion_point(field_release:valhalla.Api.status)
  
  ::valhalla::Status* temp = status_;
  status_ = NULL;
  return temp;
}
inline void Api::set_allocated_status(::valhalla::Status* status) {
  delete status_;
  status_ = status;
  if (status) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:valhalla.Api.status)
}

// optional .valhalla.Info info = 20;
inline bool Api::has_info() const {
  return !_is_default_instance_ && info_ != NULL;
}
inline void Api::clear_info() {
  if (GetArenaNoVirtual() == NULL && info_ != NULL) delete info_;
  info_ = NULL;
}
inline const ::valhalla::Info& Api::info() const {
  // @@protoc_insertion_point(field_get:valhalla.Api.info)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return info_ != NULL ? *info_ : *default_instance().info_;
#else
  return info_ != NULL ? *info_ : *default_instance_->info_;
#endif
}
inline ::valhalla::Info* Api::mutable_info() {
  
  if (info_ == NULL) {
    info_ = new ::valhalla::Info;
  }
  // @@protoc_insertion_point(field_mutable:valhalla.Api.info)
  return info_;
}
inline ::valhalla::Info* Api::release_info() {
  // @@protoc_insertion_point(field_release:valhalla.Api.info)
  
  ::valhalla::Info* temp = info_;
  info_ = NULL;
  return temp;
}
inline void Api::set_allocated_info(::valhalla::Info* info) {
  delete info_;
  info_ = info;
  if (info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:valhalla.Api.info)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace valhalla

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_api_2eproto__INCLUDED
