name: Custom build

# This one is disabled by default and can be enabled/customized based on specific needs:
# create a branch, customize this for your branch (i.e. on.push.branches member) and push

# remember: our valhalla fork will have

on:
  push:
    branches:
      - 'custom_eclever'
    paths-ignore:
      - '*.md'

jobs:
  build_wheels:
    name: Wheels - cp*, ${{ matrix.platform }}
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        # TODO: re-enable other OSs
        include:
          - image: ubuntu-latest
            platform: linux
          - image: macos-latest
            platform: macos
#          - image: windows-latest
#            platform: windows
    steps:
    - uses: actions/checkout@v2

    - name: Configure Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    # keep in-sync with the other yaml
    - name: Cache Conan
      id: cache-conan
      uses: actions/cache@v2
      if: steps.cache-conan.outputs.cache-hit != 'true'
      with:
        path: |
          ${{ github.workspace }}/conan_data
          ${{ github.workspace }}/conan_build
        key: conan-${{ matrix.platform }}-${{ hashFiles('conanfile.txt') }}
        restore-keys: |
          conan-${{ matrix.platform }}-

    - uses: pypa/cibuildwheel@v2.3.1
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.9
        CIBW_BUILD: cp310* cp39* cp38*

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl
