name: Custom build

# This one is disabled by default and can be enabled/customized based on specific needs:
# create a branch, customize this for your branch (i.e. on.push.branches member) and push

# remember: our valhalla fork will have

on:
  push:
    branches-ignore:
      - "*"
    branches:
      - "cb-custom"
    paths-ignore:
      - "*.md"
      - "*.sh"
      - "*.ipynb"
      - "*.*json"

jobs:
  build_wheels:
    name: Wheels - cp*, ${{ matrix.platform }}
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        # TODO: re-enable other OSs
        include:
          - image: ubuntu-latest
            platform: linux
            cxx: "g++-9"
    #          - image: windows-latest
    #            platform: windows
    #            cxx: 'Visual Studio'
    #          - macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # keep in-sync with the other yaml
      - name: Cache Conan
        id: cache-conan
        uses: actions/cache@v4
        if: steps.cache-conan.outputs.cache-hit != 'true'
        with:
          path: |
            ${{ github.workspace }}/conan_data
            ${{ github.workspace }}/conan_build
          key: conan-${{ matrix.platform }}-${{ hashFiles('conanfile.txt') }}
          restore-keys: |
            conan-${{ matrix.platform }}-

      #    - name: Install Conan (Windows)
      #      if: matrix.platform == 'windows'  # && steps.cache-conan.outputs.cache-hit != 'true'
      #      run: |
      #        pip install pip --upgrade
      #        pip install conan
      #        conan profile new default --detect
      #        conan profile update "settings.compiler=Visual Studio" default
      #        conan profile update "settings.compiler.version=16" default
      #        conan config set "storage.path=$env:GITHUB_WORKSPACE/conan_data"
      #        conan install --install-folder conan_build --remote conancenter .

      - uses: pypa/cibuildwheel@v2.17.0
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15
          CIBW_BUILD: cp310* cp39* cp38*

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          path: wheelhouse/*.whl
