name: Pull Request

# run test within the manylinux container: linux is quickest to run but needs access to the right system libs
# runs tests on all python versions
# push_master.yml tests all platforms but only py3.7 (lowest supported version)

on:
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
      - '*.sh'
      - '*.ipynb'
      - '*.*json'

jobs:
  build_wheels:
    name: PR - cp*, ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Lint & Style Check
      run: |
        python -m pip install -r dev-requirements.txt
        pre-commit run --all-files --show-diff-on-failure

    - uses: pypa/cibuildwheel@v2.12.1
