name: Pull Request

# run test within the manylinux container: linux is quickest to run but needs access to the right system libs
# runs tests on all python versions
# push_master.yml tests all platforms but only py3.7 (lowest supported version)

on:
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
      - '*.sh'

jobs:
  build_wheels:
    name: PR - cp*, ubuntu-latest
    runs-on: ubuntu-latest
    container: ghcr.io/gis-ops/manylinux:valhalla_python
    steps:
    - uses: actions/checkout@v2

    - name: Lint & Style Check
      run: |
        pip install black flake8
        black --check valhalla
        flake8 valhalla

    # only build the earliest supported python version
    - uses: pypa/cibuildwheel@v2.3.1
