name: Pull Request

# run test within the manylinux container: linux is quickest to run but needs access to the right system libs
# runs tests on all python versions
# push_master.yml tests all platforms but only py3.7 (lowest supported version)

on:
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
      - '*.sh'
      - '*.ipynb'
      - '*.*json'

jobs:
  build_wheels:
    name: PR - cp*, ubuntu-latest
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install Conan (MacOS)
      run: |
        pip install pip --upgrade
        pip install "conan<2.0.0"
        conan profile new default --detect
        conan config set "storage.path=${{ github.workspace }}/conan_data"
        conan install --install-folder ${{ github.workspace }}/conan_build --remote conancenter .

    - uses: pypa/cibuildwheel@v2.12.1
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.15
        CIBW_BUILD: cp37* cp311*

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl
