name: Pull Request

# run test within the manylinux container: linux is quickest to run but needs access to the right system libs
# runs tests on all python versions
# push_master.yml tests all platforms but only py3.8 (lowest supported version)

on:
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
      - '*.sh'
      - '*.ipynb'
      - '*.*json'

jobs:
  build_wheels:
    name: PR - cp*, ubuntu-latest
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Install Conan (MacOS)
      run: |
        pip install pip --upgrade
        pip install "conan<2.0.0"
        conan profile new default --detect
        conan config set "storage.path=${{ github.workspace }}/conan_data"
        conan install --install-folder ${{ github.workspace }}/conan_build --remote conancenter .

    - name: Lint & Style Check
      run: |
        python -m pip install -r dev-requirements.txt
        pre-commit run --all-files --show-diff-on-failure

    - uses: pypa/cibuildwheel@v2.17.0
      env:
        CIBW_BUILD: 'cp38* cp312*'
        MACOSX_DEPLOYMENT_TARGET: 10.15
